name: HTML Lint                                             # Define the name of the workflow

on: [push, pull_request]                                    # Trigger the workflow on push and pull request events

jobs:                                                       # Initialise jobs
  lint:                                                     # Define a job named 'lint'
    runs-on: ubuntu-latest                                  # Specify the type of virtual machine to use (Ubuntu latest version)

    container:                                              # Initialise container
      image: monkeyknuckles/html-validate                   # Use a Docker container with the html-validate image

    steps:                                                  # List of steps to execute in the job
      - name: Checkout code                                 # Step name: Checkout code from the repository
        uses: actions/checkout@v3                           # Use the checkout action to clone the repository

      - name: Copy HTML-Validate config                     # Step name: Copy markdownlint configuration file
        run: cp /app/.htmlvalidate.json $GITHUB_WORKSPACE   # Copy the .htmlvalidate.json file from the container to the workspace

      - name: Run html-validate                             # Step name: Run HTML-Validate
        run: html-validate -c=.htmlvalidate.json .          # Execute the HTML-Validate command on all HTML files in the repository