name: HTML Lint                                             # Define the name of the workflow

on: [push, pull_request]                                    # Trigger the workflow on push and pull request events

jobs:                                                       # Initialise job
  lint:                                                     # Define a job named 'lint'
    runs-on: ubuntu-latest                                  # Specifies the type of VM to provision

    container:                                              # Initialise container
      image: monkeyknuckles/html-validate                   # Points to HTML-Validate container

    steps:                                                  # List of steps to execute
      - name: Checkout code                                 # Checkout code label text
        uses: actions/checkout@v3                           # Use the checkout action to clone the repository

      - name: Copy HTML-Validate configuration file         # Set HTML-Validate configuration file label text
        run: cp /app/.htmlvalidate.json $GITHUB_WORKSPACE   # Include the HTML configuration file in the docker build

      - name: Run Lint HTML-Validate                        # Set lint HTML-Validate label text
        run: html-validate -c=.htmlvalidate.json .          # Lint all HTML files